version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - DATA_FILE=/app/sample_data.json
    restart: unless-stopped
